version: '3'

services:
 db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db:/var/lib/mysql 

volumes:
  db:
    driver: local